version: "3"
services:
  user-service:
    container_name: user-service
    build: ./user
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    networks:
      - spring-network
      
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3030:3306
    environment:
      MYSQL_DATABASE: testsecuritydb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - spring-network

  frontend_service:
    build: ./React
    container_name: frontend_service_container
    ports:
      - "3000:3000"
    # volumes:
    #   - ./React:/app
    #   - ./React/node_modules

networks:
  spring-network:
